language: python
sudo: required
dist: trusty
python:
    - 3.6.0
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.8
        - g++-4.8
        - mecab
        - libmecab-dev
        - mecab-ipadic
        - mecab-ipadic-utf8
install:
    - pip install git+https://github.com/pettan0818/mecab_direct_connecter
script:
    - python -m doctest ./mecab_direct_connecter/stopword.py
    - python -m doctest ./mecab_direct_connecter/mecab_direct_connecter.py
